### PR TITLE
merge: repository-cleanup to dev

### PR DESCRIPTION
**Pull request by nanpx**

### CODE REVIEW

**Comment by mountainraptor** [comment]
@nanpx

In the README.md, do you need to run a ```npm install``` under step 3?

**Comment by mountainraptor** [comment]
@nanpx I ran the ```npm install``` and get the following error on the docs cmd:

```
[Error: ENOENT: no such file or directory, stat '/Users/adammarkham/Software/eslint-config-simplesense/docs/rules'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/adammarkham/Software/eslint-config-simplesense/docs/rules'
  ```

**Comment by mountainraptor** [comment]
@nanpx I can get past that by making the ```/rules``` directory. Do you need to commit the empty dir?

**Comment by nanpx** [comment]
> @nanpx
> 
> In the README.md, do you need to run a `npm install` under step 3?

👍 See https://github.com/simplesenseio/eslint-config-simplesense/pull/5

**Comment by nanpx** [comment]
> @nanpx I ran the `npm install` and get the following error on the docs cmd:
> 
> ```
> [Error: ENOENT: no such file or directory, stat '/Users/adammarkham/Software/eslint-config-simplesense/docs/rules'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'stat',
>   path: '/Users/adammarkham/Software/eslint-config-simplesense/docs/rules'
> ```

See https://github.com/simplesenseio/eslint-config-simplesense/pull/6 for Node16 fixes. Interesting how `rmdir` and `rm` throw `ENOENT` when trying to remove a non-existent file in 16.x, but not 14.x. I think it's correct to do so, just interesting that it didn't previously do it.

**Review by mountainraptor — APPROVED** [review]

**Review by afeather20s — APPROVED** [review]

**Pull request merged**
